/**
 * Smoke-test for the GitHub webhook handler.
 * Generates HMAC-signed payloads for each supported event type and POSTs them
 * to the local or remote /api/github/webhooks endpoint.
 *
 * Usage:
 *   GITHUB_WEBHOOK_SECRET=<secret> pnpm tsx scripts/test-github-webhook.ts
 *   WEBHOOK_URL=https://paperclip.rk9.fi/api/github/webhooks GITHUB_WEBHOOK_SECRET=<secret> pnpm tsx scripts/test-github-webhook.ts
 *
 * Optional flags:
 *   --repo=<owner/name>   Override repository.full_name in payloads (default: mv50000/alli-audit)
 *   --only=<event>        Only run scenarios for this x-github-event header
 */

import { createHmac, randomUUID } from "node:crypto";

const WEBHOOK_URL = process.env.WEBHOOK_URL ?? "http://localhost:3100/api/github/webhooks";
const SECRET = process.env.GITHUB_WEBHOOK_SECRET ?? "";

interface Args {
  repo: string;
  only: string | null;
}

function parseArgs(argv: string[]): Args {
  const out: Args = { repo: "mv50000/alli-audit", only: null };
  for (const arg of argv) {
    if (arg.startsWith("--repo=")) out.repo = arg.slice("--repo=".length);
    else if (arg.startsWith("--only=")) out.only = arg.slice("--only=".length);
    else if (arg === "--help" || arg === "-h") {
      console.log("Usage: pnpm tsx scripts/test-github-webhook.ts [--repo=<owner/name>] [--only=<event>]");
      process.exit(0);
    }
  }
  return out;
}

function sign(body: string): string {
  return "sha256=" + createHmac("sha256", SECRET).update(body).digest("hex");
}

interface Scenario {
  event: string;
  description: string;
  expectsDispatch: boolean;
  payload: () => Record<string, unknown>;
}

function repoBlock(repo: string) {
  const [owner, name] = repo.split("/");
  return {
    full_name: repo,
    name,
    owner: { login: owner },
  };
}

function buildScenarios(repo: string): Scenario[] {
  const repository = repoBlock(repo);
  const sender = { login: "smoke-tester" };
  const baseUrl = `https://github.com/${repo}`;

  return [
    {
      event: "workflow_run",
      description: "workflow_run.completed conclusion=failure",
      expectsDispatch: true,
      payload: () => ({
        action: "completed",
        repository,
        sender,
        workflow_run: {
          id: 1001,
          workflow_id: 42,
          name: "CI",
          run_number: 314,
          head_branch: "main",
          head_sha: "abcdef1234567890",
          conclusion: "failure",
          status: "completed",
          html_url: `${baseUrl}/actions/runs/1001`,
          head_commit: { message: "fix: smoke test failure trigger" },
        },
      }),
    },
    {
      event: "workflow_run",
      description: "workflow_run.completed conclusion=success (must drop)",
      expectsDispatch: false,
      payload: () => ({
        action: "completed",
        repository,
        sender,
        workflow_run: {
          id: 1002,
          workflow_id: 42,
          name: "CI",
          run_number: 315,
          head_branch: "main",
          conclusion: "success",
          status: "completed",
          html_url: `${baseUrl}/actions/runs/1002`,
        },
      }),
    },
    {
      event: "issues",
      description: "issues.opened",
      expectsDispatch: true,
      payload: () => ({
        action: "opened",
        repository,
        sender,
        issue: {
          number: 999,
          title: "Smoke: synthetic issue",
          body: "Generated by test-github-webhook smoke",
          html_url: `${baseUrl}/issues/999`,
        },
      }),
    },
    {
      event: "issues",
      description: "issues.closed",
      expectsDispatch: true,
      payload: () => ({
        action: "closed",
        repository,
        sender,
        issue: {
          number: 999,
          title: "Smoke: synthetic issue",
          html_url: `${baseUrl}/issues/999`,
          state_reason: "completed",
        },
      }),
    },
    {
      event: "pull_request",
      description: "pull_request.opened",
      expectsDispatch: true,
      payload: () => ({
        action: "opened",
        repository,
        sender,
        pull_request: {
          number: 1234,
          title: "Smoke: synthetic PR",
          body: "Body",
          html_url: `${baseUrl}/pull/1234`,
          merged: false,
          draft: false,
          base: { ref: "main", repo: { full_name: repo } },
          head: { ref: "smoke/synth", repo: { full_name: repo } },
        },
      }),
    },
    {
      event: "pull_request",
      description: "pull_request.closed (not merged)",
      expectsDispatch: true,
      payload: () => ({
        action: "closed",
        repository,
        sender,
        pull_request: {
          number: 1234,
          title: "Smoke: synthetic PR",
          html_url: `${baseUrl}/pull/1234`,
          merged: false,
          base: { ref: "main", repo: { full_name: repo } },
          head: { ref: "smoke/synth" },
        },
      }),
    },
    {
      event: "pull_request",
      description: "pull_request.closed (merged) — auto-close path, no Slack",
      expectsDispatch: false,
      payload: () => ({
        action: "closed",
        repository,
        sender,
        pull_request: {
          number: 1235,
          title: "Smoke: synthetic merge",
          body: null,
          html_url: `${baseUrl}/pull/1235`,
          merged: true,
          base: { ref: "main", repo: { full_name: repo } },
          head: { ref: "smoke/merge" },
        },
      }),
    },
    {
      event: "pull_request",
      description: "pull_request.review_requested",
      expectsDispatch: true,
      payload: () => ({
        action: "review_requested",
        repository,
        sender,
        pull_request: {
          number: 1234,
          title: "Smoke: synthetic PR",
          html_url: `${baseUrl}/pull/1234`,
          merged: false,
          base: { ref: "main", repo: { full_name: repo } },
          head: { ref: "smoke/synth" },
        },
        requested_reviewer: { login: "reviewer-bot" },
      }),
    },
    {
      event: "release",
      description: "release.published",
      expectsDispatch: true,
      payload: () => ({
        action: "published",
        repository,
        sender,
        release: {
          tag_name: "v0.0.1-smoke",
          name: "Smoke release",
          body: "Notes",
          prerelease: false,
          html_url: `${baseUrl}/releases/tag/v0.0.1-smoke`,
        },
      }),
    },
    {
      event: "secret_scanning_alert",
      description: "secret_scanning_alert.created",
      expectsDispatch: true,
      payload: () => ({
        action: "created",
        repository,
        sender,
        alert: {
          number: 7,
          secret_type: "github_pat",
          secret_type_display_name: "GitHub PAT",
          html_url: `${baseUrl}/security/secret-scanning/7`,
        },
      }),
    },
    {
      event: "dependabot_alert",
      description: "dependabot_alert.created severity=critical",
      expectsDispatch: true,
      payload: () => ({
        action: "created",
        repository,
        sender,
        alert: {
          number: 12,
          html_url: `${baseUrl}/security/dependabot/12`,
          security_advisory: { ghsa_id: "GHSA-xxxx-xxxx", summary: "Synthetic critical advisory", severity: "critical" },
          dependency: { package: { name: "left-pad", ecosystem: "npm" } },
        },
      }),
    },
    {
      event: "dependabot_alert",
      description: "dependabot_alert.created severity=low (must drop)",
      expectsDispatch: false,
      payload: () => ({
        action: "created",
        repository,
        sender,
        alert: {
          number: 13,
          security_advisory: { severity: "low", summary: "minor" },
          dependency: { package: { name: "left-pad", ecosystem: "npm" } },
        },
      }),
    },
    {
      event: "deployment_status",
      description: "deployment_status state=failure",
      expectsDispatch: true,
      payload: () => ({
        action: "created",
        repository,
        sender,
        deployment: { environment: "prod", url: `${baseUrl}/deployments/1` },
        deployment_status: { state: "failure", description: "Synthetic failure", target_url: `${baseUrl}/runs/2` },
      }),
    },
    {
      event: "deployment_status",
      description: "deployment_status state=success (must drop)",
      expectsDispatch: false,
      payload: () => ({
        action: "created",
        repository,
        sender,
        deployment: { environment: "prod" },
        deployment_status: { state: "success" },
      }),
    },
    {
      event: "push",
      description: "push to refs/heads/main (drop unless notify_main_pushes secret enabled)",
      expectsDispatch: false,
      payload: () => ({
        ref: "refs/heads/main",
        repository,
        sender,
        commits: [{ message: "chore: smoke" }],
        head_commit: { message: "chore: smoke" },
      }),
    },
    {
      event: "check_run",
      description: "check_run.completed (must drop, redundant)",
      expectsDispatch: false,
      payload: () => ({
        action: "completed",
        repository,
        sender,
        check_run: { name: "CI", conclusion: "failure" },
      }),
    },
    {
      event: "issue_comment",
      description: "issue_comment.created with mention (requires github.mention_handles secret)",
      expectsDispatch: false,
      payload: () => ({
        action: "created",
        repository,
        sender,
        issue: { number: 999, title: "Smoke: synthetic issue", html_url: `${baseUrl}/issues/999` },
        comment: {
          body: "Hey @mv could you take a look?",
          user: { login: "smoke-tester" },
          html_url: `${baseUrl}/issues/999#issuecomment-1`,
        },
      }),
    },
  ];
}

interface Result {
  scenario: Scenario;
  status: number;
  body: Record<string, unknown> | null;
  error?: string;
}

async function send(scenario: Scenario): Promise<Result> {
  const body = JSON.stringify(scenario.payload());
  const signature = sign(body);
  const delivery = randomUUID();
  try {
    const res = await fetch(WEBHOOK_URL, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-hub-signature-256": signature,
        "x-github-event": scenario.event,
        "x-github-delivery": delivery,
        "user-agent": "paperclip-smoke/1.0",
      },
      body,
    });
    let parsed: Record<string, unknown> | null = null;
    try {
      parsed = (await res.json()) as Record<string, unknown>;
    } catch {
      parsed = null;
    }
    return { scenario, status: res.status, body: parsed };
  } catch (err) {
    return {
      scenario,
      status: 0,
      body: null,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

function fmtRow(label: string, status: number, slackDispatched: number | string, expectsDispatch: boolean, ok: boolean): string {
  const prefix = ok ? "✓" : "✗";
  return `${prefix}  ${String(status).padEnd(4)} dispatched=${String(slackDispatched).padEnd(3)} expected=${expectsDispatch ? "yes" : "no "}  ${label}`;
}

async function main() {
  if (!SECRET) {
    console.error("ERROR: GITHUB_WEBHOOK_SECRET environment variable is required");
    process.exit(2);
  }
  const args = parseArgs(process.argv.slice(2));
  const scenarios = buildScenarios(args.repo).filter((s) => !args.only || s.event === args.only);
  if (scenarios.length === 0) {
    console.error(`No scenarios match filter: ${args.only}`);
    process.exit(2);
  }
  console.log(`POST ${WEBHOOK_URL} (${scenarios.length} scenarios, repo=${args.repo})`);

  let pass = 0;
  let fail = 0;
  for (const scenario of scenarios) {
    const result = await send(scenario);
    if (result.error) {
      fail++;
      console.log(`✗  ERR  ${scenario.event}: ${result.error}`);
      continue;
    }
    const dispatched =
      typeof result.body?.slackDispatched === "number" ? (result.body.slackDispatched as number) : "?";
    const ok = result.status === 200;
    if (ok) pass++;
    else fail++;
    const label = `${scenario.event} — ${scenario.description}`;
    console.log(fmtRow(label, result.status, dispatched, scenario.expectsDispatch, ok));
  }
  console.log(`\n${pass} ok, ${fail} fail`);
  process.exit(fail === 0 ? 0 : 1);
}

main().catch((err) => {
  console.error(err);
  process.exit(2);
});
